$(document).ready(function(){
  $('#myModal').modal('show');
  $('#nav-icon1').click(function(){
    $(this).toggleClass('open');
  });
    $('#maior').click(function(){
      $('#myModal').modal('hide');
    });
  });
